function f = QuadrotorStateFcn(in1,in2)
%QuadrotorStateFcn
%    F = QuadrotorStateFcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Jan-2023 13:18:08

phi_t = in1(4,:);
phi_dot_t = in1(10,:);
psi_t = in1(6,:);
psi_dot_t = in1(12,:);
theta_t = in1(5,:);
theta_dot_t = in1(11,:);
u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x_dot_t = in1(7,:);
y_dot_t = in1(8,:);
z_dot_t = in1(9,:);
t2 = cos(phi_t);
t3 = cos(psi_t);
t4 = cos(theta_t);
t5 = sin(phi_t);
t6 = sin(psi_t);
t7 = sin(theta_t);
t8 = phi_t.*2.0;
t9 = psi_dot_t.^2;
t10 = theta_t.*2.0;
t15 = u1+u2+u3+u4;
t11 = t2.^2;
t12 = t4.^2;
t13 = sin(t8);
t14 = sin(t10);
t16 = 1.0./t12;
mt1 = [x_dot_t;y_dot_t;z_dot_t;phi_dot_t;theta_dot_t;psi_dot_t;(t15.*(t5.*t6+t2.*t3.*t7))./2.0;t15.*(t3.*t5-t2.*t6.*t7).*(-1.0./2.0);(t2.*t4.*t15)./2.0-9.81e+2./1.0e+2];
mt2 = [(t16.*(u2.*-1.15e+2+u4.*1.15e+2-t7.*u1.*9.2e+1+t7.*u2.*9.2e+1-t7.*u3.*9.2e+1+t7.*u4.*9.2e+1+t11.*u2.*5.5e+1-t11.*u4.*5.5e+1+phi_dot_t.*t14.*theta_dot_t.*2.3e+1+psi_dot_t.*t4.*theta_dot_t.*1.058e+3+t7.*t11.*u1.*4.4e+1-t7.*t11.*u2.*4.4e+1+t7.*t11.*u3.*4.4e+1-t7.*t11.*u4.*4.4e+1-t11.*t12.*u2.*5.5e+1+t11.*t12.*u4.*5.5e+1-psi_dot_t.*t4.*t11.*theta_dot_t.*5.06e+2-t2.*t5.*t9.*t12.*5.06e+2-psi_dot_t.*t4.^3.*t11.*theta_dot_t.*5.06e+2+t2.*t5.*t12.*theta_dot_t.^2.*5.06e+2+phi_dot_t.*t4.*t7.*t11.*theta_dot_t.*5.06e+2-t2.*t4.*t5.*t7.*u1.*5.5e+1+t2.*t4.*t5.*t7.*u3.*5.5e+1+phi_dot_t.*psi_dot_t.*t2.*t5.*t7.*t12.*5.06e+2))./5.52e+2];
mt3 = [((t4.*u1.*6.0e+1-t4.*u3.*6.0e+1+t13.*u1.*2.2e+1-t13.*u2.*2.2e+1+t13.*u3.*2.2e+1-t13.*u4.*2.2e+1+phi_dot_t.*psi_dot_t.*t12.*5.52e+2+t4.*t11.*u1.*5.5e+1-t4.*t11.*u3.*5.5e+1-phi_dot_t.*psi_dot_t.*t11.*t12.*5.06e+2+t7.*t9.*t11.*t12.*5.06e+2+t2.*t5.*t7.*u2.*5.5e+1-t2.*t5.*t7.*u4.*5.5e+1+phi_dot_t.*t2.*t4.*t5.*theta_dot_t.*5.06e+2-psi_dot_t.*t2.*t4.*t5.*t7.*theta_dot_t.*5.06e+2).*(-1.0./5.52e+2))./t4];
mt4 = [(t16.*(u1.*-9.2e+1+u2.*9.2e+1-u3.*9.2e+1+u4.*9.2e+1-t7.*u2.*1.15e+2+t7.*u4.*1.15e+2+t11.*u1.*4.4e+1-t11.*u2.*4.4e+1+t11.*u3.*4.4e+1-t11.*u4.*4.4e+1+phi_dot_t.*t4.*theta_dot_t.*4.6e+1+psi_dot_t.*t14.*theta_dot_t.*5.29e+2+t7.*t11.*u2.*5.5e+1-t7.*t11.*u4.*5.5e+1+phi_dot_t.*t4.*t11.*theta_dot_t.*5.06e+2-t2.*t4.*t5.*u1.*5.5e+1+t2.*t4.*t5.*u3.*5.5e+1+phi_dot_t.*psi_dot_t.*t2.*t5.*t12.*5.06e+2-psi_dot_t.*t4.*t7.*t11.*theta_dot_t.*5.06e+2-t2.*t5.*t7.*t9.*t12.*5.06e+2))./5.52e+2];
f = [mt1;mt2;mt3;mt4];
